### ISSUE TITLE
how do i get translucent background?

### ISSUE THREAD

**Issue by therajat08** [cannibalox/ono-sendai_obsdn#1]
after plugin installation, in dark mode, there is no background transparency. How do i get that effect as shown in one of your snapshots. 
Also how do i turn off the feature where only the current line  is getting highlighted ?

**Comment by cannibalox** [comment]
make sure you enabled the translucency plugin inside obsidian's settings first, then refresh obsidian with `ctrl R`.
let me know if it works. I need to update the theme to match the latest changes in the core.

**Comment by therajat08** [comment]
Okay, so i it says translucency isn't supported on linux. So i guess can't be helped there. 
Another question: Is there a way to show the vault name in the top right corner, Like this : `\\Obsidian 0.9.11\vault-name`

**Comment by cannibalox** [comment]
sorry, I can't add that
