### ISSUE TITLE
Font not correct on edit mode

### ISSUE THREAD

**Issue by edofe99** [cannibalox/ono-sendai_obsdn#6]
There is an issue that cause font to be the standard one during editing mode and then going to Cairo on preview mode. 

I resolved the issue placing this string right after initial credits:
```
/* Ono-Sendai for Obsidian - v202009250100 v0.9.00 by _ph / www.hpx1.com */
/* consider leaving credits or putting a thank you if you use this theme as a starter kit */
/* free to use, share and modify -*/


:root {
--default-font: Cairo;
}

....other code
```

Hope this help. Thank's for the amazing theme.

**Comment by cannibalox** [comment]
updating with the fix, thanks !
